// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPxXuNO02vF1ZGJxwOw5tuKkVSFy-HhjE',
    appId: '1:813037135797:web:fb7f5ac3b81b266c689bfc',
    messagingSenderId: '813037135797',
    projectId: 'rest-ici-burkina',
    authDomain: 'rest-ici-burkina.firebaseapp.com',
    storageBucket: 'rest-ici-burkina.firebasestorage.app',
    measurementId: 'G-QM9PD9X7JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2rr86uAcsIGjLTmX4lbwQOnfgoid5E10',
    appId: '1:813037135797:android:09475aea62400e57689bfc',
    messagingSenderId: '813037135797',
    projectId: 'rest-ici-burkina',
    storageBucket: 'rest-ici-burkina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0l0f1Evjy9wlOjIj_n6EoLITDA8kMf_s',
    appId: '1:813037135797:ios:947c5b88a1c91fcc689bfc',
    messagingSenderId: '813037135797',
    projectId: 'rest-ici-burkina',
    storageBucket: 'rest-ici-burkina.firebasestorage.app',
    androidClientId: '813037135797-a72ot3e5tueme6ctm17mcp0r6p9cubom.apps.googleusercontent.com',
    iosClientId: '813037135797-eco5hcduuv1c8sgcnqbajtk849i5im95.apps.googleusercontent.com',
    iosBundleId: 'com.safrimatbf.resticiAdmin',
  );
}
